# Generated by Django 3.0.8 on 2020-10-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('para1', models.TextField(max_length=500)),
                ('para2', models.TextField(max_length=500)),
                ('highlighter', models.TextField(max_length=300)),
            ],
        ),
    ]
