# Generated by Django 3.0.8 on 2023-09-12 13:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('para1', models.TextField(max_length=500)),
                ('para2', models.TextField(max_length=500)),
                ('highlighter', models.TextField(max_length=300)),
                ('dislikes', models.ManyToManyField(related_name='dislike_blog', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='like_blog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
