# Generated by Django 3.0.8 on 2020-10-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('title', models.TextField(max_length=200)),
                ('para1', models.TextField(max_length=1000)),
                ('para2', models.TextField(max_length=1000)),
                ('hightlighter', models.TextField(max_length=400)),
                ('para3', models.TextField(max_length=100)),
            ],
        ),
    ]
