# Generated by Django 3.0.8 on 2020-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='cour_desc',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='cour_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='courses',
            name='cour_star',
            field=models.FloatField(default=None),
        ),
    ]
