# Generated by Django 3.0.8 on 2020-10-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0002_auto_20200815_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='tittle',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
