# Generated by Django 3.0.8 on 2020-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_courses_tittle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='tittle',
        ),
        migrations.AlterField(
            model_name='courses',
            name='cour_name',
            field=models.CharField(max_length=50),
        ),
    ]
