# Generated by Django 3.0.8 on 2020-10-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_auto_20201015_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python_name', models.CharField(max_length=50)),
                ('python_link', models.URLField(max_length=100)),
                ('python_desc', models.CharField(max_length=100)),
                ('python_star', models.FloatField(default=None)),
                ('python_price', models.IntegerField(default=None)),
            ],
        ),
    ]
