# Generated by Django 3.0.8 on 2020-10-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0005_python'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Python',
        ),
    ]
